### ISSUE TITLE
一个关于验证码训练的问题

### ISSUE THREAD

**Issue by ResolveWang** [littlepai/Unofficial-Zhihu-API#6]
您好，非常感谢您的repo，我是深度学习的初学者，有一个问题想请教一下，您这个repo中使用自己画的验证码，然后把它迁移到知乎的真实验证码上来，请问核心代码是这里吗？
```python3
if FLAGS.restore:
    ckpt = tf.train.latest_checkpoint(FLAGS.checkpoint_dir)
    if ckpt:
        # 恢复的时候global_step也会被恢复
        saver.restore(sess, ckpt)
        print('restore from the checkpoint{0}'.format(ckpt))
```

其实就是将训练的模型拿过来接着跟着真实的验证码训练吗？

如果是这样的话，初始训练的神经网络权重之类的应该会改变吧？会对训练结果有影响吗？如果不是这样的话，我想问问迁移学习的核心代码是在哪里啊？

期待您的答复，感谢！

**Comment by littlepai** [comment]
自己画的验证码，可以无限多，把模型训练好之后，模型就具备了很好的特征提取能力了，这个时候让真实验证码微调是没问题的，就像BERT，微调是可行的
